package org.iana.ticketing;

/**
 * <p>
 * This interface serves as a boundary interface to hide the communication details with the ticketing system
 * system used internally by ICANN to process domain modification transactions.
 * </p>
 *
 * @author Patrycja Wegrzynowicz
 * @author Jakub Laszkiewicz
 */
public interface TicketingService {

    /**
     * Returns a new ticket identifier generated by RequestTracker.
     *
     * @return
     */
    public long generateID();

    // todo: identify the required methods

    public long createTicket(String tld, String label) throws TicketingException;

    public void setIanaState(long ticketId, String stateName) throws TicketingException;

    public void closeTicket(long ticketId) throws TicketingException;
}
